import {
  ArrowUpRight,
  BookOpen,
  Building,
  CalendarDays,
  CircleDollarSign,
  ClipboardList,
  GraduationCap,
  ImageIcon,
  Layers,
  LayoutGrid,
  PencilLine,
  Receipt,
  Settings,
  SlidersHorizontal,
  UserCheck,
  UserCircle,
  Wallet,
} from 'lucide-react';
import { type MenuConfig } from './types';

export const MENU_SIDEBAR: MenuConfig = [
  /* ----- Platform admin (super_admin only, hidden while impersonating) ----- */
  {
    heading: 'Platform',
    roles: ['super_admin'],
    hideWhenImpersonating: true,
  },
  {
    title: 'Overview',
    icon: LayoutGrid,
    path: '/admin',
    roles: ['super_admin'],
    hideWhenImpersonating: true,
  },
  {
    title: 'Schools',
    icon: Building,
    path: '/admin/schools',
    roles: ['super_admin'],
    hideWhenImpersonating: true,
  },
  {
    title: 'Platform Settings',
    icon: Settings,
    path: '/admin/platform-settings',
    roles: ['super_admin'],
    hideWhenImpersonating: true,
  },

  /* ----- Tenant-scoped (school roles; super_admin only while impersonating) ----- */
  {
    title: 'Dashboard',
    icon: LayoutGrid,
    path: '/dashboard',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    heading: 'School Management',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Students',
    icon: GraduationCap,
    path: '/students',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Teachers',
    icon: UserCheck,
    path: '/teachers',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Classes & Arms',
    icon: Layers,
    path: '/academic/classes',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Subjects',
    icon: BookOpen,
    path: '/academic/subjects',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Academic Sessions',
    icon: CalendarDays,
    path: '/academic/sessions',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Promotion Manager',
    icon: ArrowUpRight,
    path: '/academic/promotions',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'School Branding',
    icon: ImageIcon,
    path: '/school/branding',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },

  {
    heading: 'College Report',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Score Entry',
    icon: PencilLine,
    path: '/results/entry',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'All Results',
    icon: ClipboardList,
    path: '/results',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Report Setup',
    icon: SlidersHorizontal,
    path: '/college-report/setup',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Weekly Evaluation',
    icon: ClipboardList,
    path: '/evaluations/entry',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Evaluation Rubrics',
    icon: SlidersHorizontal,
    path: '/evaluations/rubrics',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },

  {
    heading: 'Fees',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Fees Dashboard',
    icon: Wallet,
    path: '/fees',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Invoices',
    icon: Receipt,
    path: '/fees/invoices',
    roles: ['super_admin', 'school_admin', 'teacher'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Fee Structures',
    icon: Layers,
    path: '/fees/structures',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },
  {
    title: 'Fee Categories',
    icon: CircleDollarSign,
    path: '/fees/categories',
    roles: ['super_admin', 'school_admin'],
    onlyWhenImpersonating: true,
  },

  /* ----- Universal account ----- */
  { heading: 'Account' },
  {
    title: 'Account Settings',
    icon: UserCircle,
    path: '/account/settings',
  },
];
